version: '2'

volumes:
  data:

services:
  tf:
    build: .
    volumes:
      - ./:/tensorbuilder
    ports:
      - "8885:8888"
    command: bash -c "cd /tensorbuilder && python setup.py install && cd /notebooks && /run_jupyter.sh"

  pdoc:
    # update gh-pages => git subtree push --prefix docs/tensorbuilder origin gh-pages
    build: .
    volumes:
      - ./:/tensorbuilder
    command: bash -c "cd /tensorbuilder && PYTHONPATH= pdoc --html-dir=./docs --html tensorbuilder --only-pypath --overwrite"
